name: Plan
main: com.djrapitops.plandemog.PlanDemog
version: 1.0.0

commands:
  plan:
    usage: /<command> <name>
    description: base command
  inspect:
    usage: /plan inspect <name>
    description: inspect player data
  analyze:
    usage: /plan analyze
    description: analyze all players' data, add -refresh to refresh analysis.
  reload:
    usage: /plan reload
    description: reload plugin config
  search:
    usage: /plan <search terms> -p add -p to make not search playername

depend:
- Plan

permissions:
  pland.?:
    description: Help command
    default: true